// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: presence.proto

package presence

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	regexp "regexp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _regex_UserListRequest_SystemCode = regexp.MustCompile(`^([ABZ])?$`)

func (this *UserListRequest) Validate() error {
	if !_regex_UserListRequest_SystemCode.MatchString(this.SystemCode) {
		return github_com_mwitkow_go_proto_validators.FieldError("SystemCode", fmt.Errorf(`value '%v' must be a string conforming to regex "^([ABZ])?$"`, this.SystemCode))
	}
	return nil
}
func (this *UserRequest) Validate() error {
	return nil
}
func (this *UserListResponse) Validate() error {
	for _, item := range this.Users {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Users", err)
			}
		}
	}
	return nil
}
func (this *UserResponse) Validate() error {
	return nil
}
